
/** Ticket Types */

export const CREATE_TICKET = 'CREATE_TICKET';
export const EDIT_TICKET = 'EDIT_TICKET';

export const GET_TICKETS = 'GET_TICKETS';
export const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS';

export const CHANGE_TICKET_STATUS = 'CHANGE_TICKET_STATUS';

export const GET_TICKET_BY_ID = 'GET_TICKET_BY_ID';
export const GET_TICKET_BY_ID_SUCCESS = 'GET_TICKET_BY_ID_SUCCESS';

export const GET_SOLD_TICKETS = 'GET_SOLD_TICKETS';
export const GET_SOLD_TICKETS_SUCCESS = 'GET_SOLD_TICKETS_SUCCESS';

export const GET_SOLD_TICKETS_INFORMATION = 'GET_SOLD_TICKETS_INFORMATION';
export const GET_SOLD_TICKETS_INFORMATION_SUCCESS = 'GET_SOLD_TICKETS_INFORMATION_SUCCESS';

/** End */