/**Organization types */

/**Organization types */
export const CREATE_ORGANIZATION_CATEGORY = 'CREATE_ORGANIZATION_CATEGORY';
export const EDIT_ORGANIZATION_CATEGORY = 'EDIT_ORGANIZATION_CATEGORY';
export const DELETE_ORGANIZATION_CATEGORY = 'DELETE_ORGANIZATION_CATEGORY';
export const GET_ORGANIZATION_CATEGORY = 'GET_ORGANIZATION_CATEGORY';
export const GET_ORGANIZATION_CATEGORY_SUCCESS = 'GET_ORGANIZATION_CATEGORY_SUCCESS';
export const GET_ORGANIZATION_CATEGORY_BY_ID = 'GET_ORGANIZATION_CATEGORY_BY_ID';

