/** Events Types */
export const GET_EVENTS = "GET_EVENTS";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";

export const CREATE_EVENT = "CREATE_EVENT";
export const EDIT_EVENT = "EDIT_EVENT";

export const EDIT_EVENT_ACCESS = "EDIT_EVENT_ACCESS";

export const EDIT_EVENT_ACCESS_LIST = "EDIT_EVENT_ACCESS_LIST";

export const DELETE_EVENTS = "DELETE_EVENTS";

export const GET_EVENT_BY_ID = "GET_EVENT_BY_ID";
export const GET_EVENT_BY_ID_SUCCESS = "GET_EVENT_BY_ID_SUCCESS";

export const CHANGE_EVENT_STATUS = "CHANGE_EVENT_STATUS";
/** End */

/** Events Tags, Categories, Types */
export const GET_EVENT_TAGS = 'GET_EVENT_TAGS'
export const GET_EVENT_TAGS_SUCCESS = 'GET_EVENT_TAGS_SUCCESS'

export const GET_EVENT_CATEGORIES = 'GET_EVENT_CATEGORIES'
export const GET_EVENT_CATEGORIES_SUCCESS = 'GET_EVENT_CATEGORIES_SUCCESS'
/** End */

/** Rsvp Actions */
export const GET_EVENT_RSVP = 'GET_EVENT_RSVP'
export const GET_EVENT_RSVP_SUCCESS = 'GET_EVENT_RSVP_SUCCESS'
/** End */

/** Event Note */
export const GET_EVENT_SPONSORS_FOR_EDIT = 'GET_EVENT_SPONSORS_FOR_EDIT';
export const GET_EVENT_SPONSORS_FOR_EDIT_SUCCESS = 'GET_EVENT_SPONSORS_FOR_EDIT_SUCCESS';

export const EDIT_NOTE = 'EDIT_NOTE'
/** End */