/**Organization types */

/**Organization types */
export const CREATE_ORGANIZATION = 'CREATE_ORGANIZATION';
export const EDIT_ORGANIZATION = 'EDIT_ORGANIZATION';
export const DELETE_ORGANIZATION = 'DELETE_ORGANIZATION';


export const GET_ORGANIZATION = 'GET_ORGANIZATION';
export const GET_ORGANIZATION_SUCCESS = 'GET_ORGANIZATION_SUCCESS';
export const GET_ORGANIZATION_BY_ID = 'GET_ORGANIZATION_BY_ID';
export const GET_ORGANIZATION_BY_ID_SUCCESS = 'GET_ORGANIZATION_BY_ID_SUCCESS';
export const GET_ORGANIZATION_BY_ID_ORG = 'GET_ORGANIZATION_BY_ID_ORG';
export const GET_ORGANIZATION_BY_ID_ORG_SUCCESS = 'GET_ORGANIZATION_BY_ID_ORG_SUCCESS';

/**Claims types */

export const GET_CLAIMS = 'GET_CLAIMS';
export const GET_CLAIMS_SUCCESS = 'GET_CLAIMS_SUCCESS';
export const APPROVE_CLAIMS = 'APPROVE_CLAIMS';
export const REJECT_CLAIMS = 'REJECT_CLAIMS';

/**Edits types */
export const GET_EDITS = 'GET_EDITS';
export const GET_EDITS_SUCCESS = 'GET_EDITS_SUCCESS';
export const ACCEPT_OR_REJECT_EDIT = 'ACCEPT_OR_REJECT_EDIT';

/**Status */
export const SET_STATUS = 'SET_STATUS';

/**Manager */
export const REMOVE_MANAGER = 'REMOVE_MANAGER';

/**Sponsoring */
export const GET_PENDING_SPONSORS = 'GET_PENDING_SPONSORS';
export const GET_PENDING_SPONSORS_SUCCESS = 'GET_PENDING_SPONSORS_SUCCESS';

export const GET_EVENT_SPONSORS = 'GET_EVENT_SPONSORS';
export const GET_EVENT_SPONSORS_SUCCESS = 'GET_EVENT_SPONSORS_SUCCESS';

export const GET_EVENT_SPONSORS_FOR_EDIT = 'GET_EVENT_SPONSORS_FOR_EDIT';
export const GET_EVENT_SPONSORS_FOR_EDIT_SUCCESS = 'GET_EVENT_SPONSORS_FOR_EDIT_SUCCESS';

export const APPROVE_REJECT_SPONSOR = 'APPROVE_REJECT_SPONSOR';

/**Org */
export const SEARCH_ORG = 'SEARCH_ORG';
export const FILTER_ORG = 'FILTER_ORG';
export const FILTER_ORG_DEFAULT = 'FILTER_ORG_DEFAULT';
export const FILTER_ORG_BY_STATUS = 'FILTER_ORG_BY_STATUS';

