export const UPDATE_AVATAR = 'UPDATE_AVATAR';
export const UPDATE_AVATAR_SUCCESS = 'UPDATE_IMAGE_SUCCESS';
export const UPDATE_AVATAR_ERROR = 'UPDATE_IMAGE_ERROR';

export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_ERROR = 'EDIT_PROFILE_ERROR';

export const SET_USER = 'SET_USER';
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS';
export const SET_USER_ERROR = 'SET_USER_ERROR';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

// Edit profile types
export const GET_MY_PROFILE = 'GET_MY_PROFILE';
export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS';

export const EDIT_MY_PROFILE = 'EDIT_MY_PROFILE';
export const EDIT_MY_PROFILE_SUCCESS = 'EDIT_MY_PROFILE_SUCCESS';
export const EDIT_MY_PROFILE_FAIL = 'EDIT_MY_PROFILE_FAIL';

export const EDIT_MY_ORGANIZATION = 'EDIT_MY_ORGANIZATION';
export const EDIT_MY_ORGANIZATION_SUCCESS = 'EDIT_MY_ORGANIZATION_SUCCESS';
export const EDIT_MY_ORGANIZATION_FAIL = 'EDIT_MY_ORGANIZATION_FAIL';

export const EDIT_MY_PASSWORD = 'EDIT_MY_PASSWORD';
export const EDIT_MY_PASSWORD_SUCCESS = 'EDIT_MY_PASSWORD_SUCCESS';
export const EDIT_MY_PASSWORD_FAIL = 'EDIT_MY_PASSWORD_FAIL';

export const REMOVE_ERROR = 'REMOVE_ERROR';
export const REMOVE_SUCCESS = 'REMOVE_SUCCESS';

export const UPDATE_MY_AVATAR = 'UPDATE_MY_AVATAR';
export const UPDATE_MY_AVATAR_SUCCESS = 'UPDATE_MY_AVATAR_SUCCESS';
