
/** Organization Actions */

/** My Organizations */

export const CREATE_ORGANIZATION = 'CREATE_ORGANIZATION';
export const EDIT_ORGANIZATION = 'EDIT_ORGANIZATION';

export const GET_ORGANIZATION_SOCIALS = 'GET_ORGANIZATION_SOCIALS';
export const GET_ORGANIZATION_SOCIALS_SUCCESS = 'GET_ORGANIZATION_SOCIALS_SUCCESS';
export const EDIT_ORGANIZATION_SOCIALS = 'EDIT_ORGANIZATION_SOCIALS';

export const GET_ORGANIZATION = 'GET_ORGANIZATION';

export const GET_ORG_BY_USER = 'GET_ORG_BY_USER';
export const GET_ORG_BY_USER_SUCCESS = 'GET_ORG_BY_USER_SUCCESS';

export const GET_ORGANIZATION_BY_ID = 'GET_ORGANIZATION_BY_ID';
export const GET_ORGANIZATION_BY_ID_SUCCESS = 'GET_ORGANIZATION_BY_ID_SUCCESS';

export const GET_CURRENT_ORG = 'GET_CURRENT_ORG';
export const SET_CURRENT_ORG = 'SET_CURRENT_ORG';

/** End */

/** Organization Categories */
export const GET_ORG_CATEGORIES = 'GET_ORG_CATEGORIES';
export const GET_ORG_CATEGORIES_SUCCESS = 'GET_ORG_CATEGORIES_SUCCESS';
/** End */