/**Invites types */

// Make Member Types

export const MAKE_MEMBER_INVITE = 'MAKE_MEMBER_INVITE';
export const MAKE_MEMBER_INVITE_SUCCESS = 'MAKE_MEMBER_INVITE_SUCCESS';

// Member Types

export const MEMBER_INVITE = 'MEMBER_INVITE';
export const MEMBER_INVITE_SUCCESS = 'MEMBER_INVITE_SUCCESS';
export const MEMBER_INVITE_FAIL = 'MEMBER_INVITE_FAIL';

// Organizer Types

export const ORGANIZER_INVITE = 'ORGANIZER_INVITE';
export const ORGANIZER_INVITE_SUCCESS = 'ORGANIZER_INVITE_SUCCESS';

export const REMOVE_STATUS = 'REMOVE_STATUS';




export const SET_ROLE_INVITE = 'SET_ROLE_INVITE'
