/**Events types */

// For Get Events
export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';

// For Create Events
export const CREATE_EVENTS = 'CREATE_EVENTS';

// For Edit Events
export const EDIT_EVENTS = 'EDIT_EVENTS';

// For Delete Event
export const DELETE_EVENTS = 'DELETE_EVENTS';

// For SearchPage Events

export const SEARCH_EVENTS = 'SEARCH_EVENTS';

//For Filter Events
export const FILTER_ORGANIZERS_BY_DATE = 'FILTER_ORGANIZERS_BY_DATE';
export const FILTER_ORGANIZERS_BY_DATE_SUCCESS = 'FILTER_ORGANIZERS_BY_DATE_SUCCESS';
export const FILTER_ORGANIZERS_BY_AZ = 'FILTER_ORGANIZERS_BY_AZ';
export const FILTER_ORGANIZERS_BY_DEFAULT = 'FILTER_ORGANIZERS_BY_DEFAULT';
export const FILTER_ORGANIZERS_BY_AZ_SUCCESS = 'FILTER_ORGANIZERS_BY_AZ_SUCCESS';
export const FILTER_TITLE_BY_AZ = 'FILTER_TITLE_BY_AZ';
export const FILTER_EVENTS_BY_TYPE = 'FILTER_EVENTS_BY_TYPE';

// export const CREATE_NEW_LIST = 'CREATE_NEW_LIST';

//Events status

export const SUBMIT_EVENT = 'SUBMIT_EVENT';
export const APPROVE_EVENT = 'APPROVE_EVENT';
export const REJECT_EVENT = 'REJECT_EVENT';
export const UNPUBLISH_EVENT = 'UNPUBLISH_EVENT';
export const PUBLISH_EVENT = 'PUBLISH_EVENT';



export const SET_EVENT_STATUS = 'SET_EVENT_STATUS'

//Event Sponsor
export const REMOVE_SPONSORS_LIST = 'REMOVE_SPONSORS_LIST';
export const GET_PENDING_SPONSORS = 'GET_PENDING_SPONSORS';
export const GET_PENDING_SPONSORS_SUCCESS = 'GET_PENDING_SPONSORS_SUCCESS';

export const GET_EVENT_SPONSORS = 'GET_EVENT_SPONSORS';
export const GET_EVENT_SPONSORS_SUCCESS = 'GET_EVENT_SPONSORS_SUCCESS';

export const GET_EVENT_SPONSORS_FOR_EDIT = 'GET_EVENT_SPONSORS_FOR_EDIT';
export const GET_EVENT_SPONSORS_FOR_EDIT_SUCCESS = 'GET_EVENT_SPONSORS_FOR_EDIT_SUCCESS';

export const APPROVE_REJECT_SPONSOR = 'APPROVE_REJECT_SPONSOR';

export const EDIT_SPONSOR_NOTE = 'EDIT_SPONSOR_NOTE';

