export const POST_MAIL = 'POST_MAIL';
export const POST_MAIL_SUCCESS = 'POST_MAIL_SUCCESS';
export const POST_MAIL_FAIL = 'POST_MAIL_FAIL';
export const SUBSCRIBE_NEWS = 'SUBSCRIBE_NEWS';
export const SUBSCRIBE_NEWS_SUCCESS = 'SUBSCRIBE_NEWS_SUCCESS';
export const SUBSCRIBE_NEWS_FAIL = 'SUBSCRIBE_NEWS_FAIL';


export const REMOVE_ERROR = 'REMOVE_ERROR'