
/** Member Types */
export const INVITE_MEMBER = 'INVITE_MEMBER';

export const EDIT_ROLE = 'EDIT_ROLE';
export const EDIT_ROLE_SUCCESS = 'EDIT_ROLE_SUCCESS';

export const GET_MEMBERS = 'GET_MEMBERS';
export const GET_MEMBERS_SUCCESS = 'GET_MEMBERS_SUCCESS';

export const GET_ALL_MEMBERS = 'GET_ALL_MEMBERS';
export const GET_ALL_MEMBERS_SUCCESS = 'GET_ALL_MEMBERS_SUCCESS';

export const DELETE_MEMBERS = 'DELETE_MEMBERS';

/** End */

/** Tag Types */
export const GET_TAGS = 'GET_TAGS';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';

export const CREATE_TAG = 'CREATE_TAG';
export const EDIT_TAG = 'EDIT_TAG';
export const DELETE_TAG = 'DELETE_TAG';

export const ADD_TAG_TO_MEMBER = 'ADD_TAG_TO_MEMBER';
export const REMOVE_TAG_FROM_MEMBER = 'REMOVE_TAG_FROM_MEMBER';

/** End */

/** User List Types */

export const CREATE_USER_LIST = 'CREATE_USER_LIST'

export const GET_USER_GROUP_LIST = 'GET_USER_GROUP_LIST'
export const GET_USER_GROUP_LIST_SUCCESS = 'GET_USER_GROUP_LIST_SUCCESS'

export const GET_GROUP_LIST_BY_ID = 'GET_GROUP_LIST_BY_ID'
export const GET_GROUP_LIST_BY_ID_SUCCESS = 'GET_GROUP_LIST_BY_ID_SUCCESS'
export const REMOVE_GROUP_LIST_BY_ID = 'REMOVE_GROUP_LIST_BY_ID'

export const GET_GROUP_LIST_ALL_USERS_BY_ID_SUCCESS = 'GET_GROUP_LIST_ALL_USERS_BY_ID_SUCCESS'

export const ASSIGN_USERS_TO_LIST = 'ASSIGN_USERS_TO_LIST'

export const ASSIGN_USERS_TO_GROUP_LIST = 'ASSIGN_USERS_TO_GROUP_LIST'
export const UNASSIGN_USERS_TO_GROUP_LIST = 'UNASSIGN_USERS_TO_GROUP_LIST'

export const DUPLICATE_LIST = 'DUPLICATE_LIST'

export const DELETE_GROUPED_LIST = 'DELETE_GROUPED_LIST'

/** End */




