export const MODAL_NAMES = {
    /* */
    INVITE_MEMBER: 'INVITE_MEMBER',
    ADD_TRANSACTION: 'ADD_TRANSACTION',
    DELETE_MODAL: 'DELETE_MODAL',
    CREATE_ORGANIZATION: 'CREATE_ORGANIZATION',
    DUPLICATE_LIST: 'DUPLICATE_LIST',
    CREATE_NEW_LIST: 'CREATE_NEW_LIST',
    ADD_USER_TO_LIST: 'ADD_USER_TO_LIST',
    CONFIRM_LIST_DELETION: 'CONFIRM_LIST_DELETION',
    CREATE_EVENT: 'CREATE_EVENT',
    EDIT_EVENT: 'EDIT_EVENT',
    EVENT_RESPONSE: 'EVENT_RESPONSE',
    ADD_SELECTED: 'ADD_SELECTED',
    DELETE_TAG: 'DELETE_TAG',
    ADD_SELECTED_MEMBERS: 'ADD_SELECTED_MEMBERS',
};
